defaults:
  - process: process2
  - model: model1
  - _self_

raw: 
  path: data/raw/Employee.csv

processed:
  dir: data/processed
  X_train: 
    name: X_train.csv
    path: ${processed.dir}/${processed.X_train.name}
  X_test:
    name: X_test.csv
    path: ${processed.dir}/${processed.X_test.name}
  y_train: 
    name: y_train.csv
    path: ${processed.dir}/${processed.y_train.name}
  y_test:
    name: y_test.csv
    path: ${processed.dir}/${processed.y_test.name}  

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}

model:
  dir: models
  name: xgboost
  path: ${model.dir}/${model.name}


# mlflow_tracking_ui: https://dagshub.com/databootcamp2021/employee_future.mlflow
# mlflow_USERNAME: databootcamp2021
# mlflow_PASSWORD: e4a7be0be4b56a7112ad75969ed9cd5f51c57f5d

# # mlflow_tracking_ui: http://127.0.0.1:5000
# mlflow_tracking_ui: file:D:\kieu_ntm\BRC_Design_Docs\MLOps\MLOps_Bootcamp\Practice_MLOps\15_mlops_project\mlruns\
mlflow_tracking_ui: https://dagshub.com/Brycenvn/customer_churn.mlflow
mlflow_USERNAME: Brycenvn
mlflow_PASSWORD: 9579d0ed9e1723855a0cf0fb3512b13257871c11